# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JLahSmekm-A_a1wtDO00vVxIPezckxvx
"""

import requests
import bs4
import prettytable

url = 'https://www.cwb.gov.tw/V8/C/W/TemperatureTop/County_TMax_T.html'

response = requests.get(url,
                        headers = {'user-agent' : 'Mozilla/5.0'}, 
                        params = {'ID' : 'Fri%20May%2013%202022%2017:42:51%20GMT+0800%20(GMT+08:00)'}
                        )
# print(response.text)# get

p1 = bs4.BeautifulSoup(response.text, 'html.parser')
t1 = prettytable.PrettyTable(['地區', '氣溫'])  # set table title
# print(p1) # correct

tems = p1.find_all('tr')

for data in tems:
  t1.add_row([data.find('th').text, data.find('span').text])

print(t1)